name: Buid and Deploy Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production
      deployment: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: SSH Remote Pull
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          . /home/deploy/.bashrc
          && cd /var/www/labs/pomo
          && git pull
          && npm i
          && npm run build